name: Auth tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    name: Api Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Step 1 Check version Newman and Node
        run: |
          newman --version
          node --version
            
      - name: Step 2 Install Newman-Reporter-Htmlextra
        run: sudo npm install -g newman-reporter-htmlextra
        
      - name: Step 3 Execute collection
        run: newman run auth_collection.json -e env-QaCoders.json -g env-globals.json --delay-request 1 --reporters cli,htmlextra --reporter-htmlextra-export ./results/Report.html

      - name: Step 4 Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
            name: report
            path: ./results/Report.html

  deploy:
    name: Deploy GitHub Pages 🌐
    runs-on: ubuntu-latest
    needs: 
      - build
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: https://marilliadantas.github.io/thementalist-academy-front-robot/report.html
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5
                  
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with: 
          name: robot-framework-report-web
                  
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./
                  
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4